org: leomontoya
service: api-cines

provider:
  name: aws
  runtime: python3.13
  # Default memory size for functions (default: 256MB)
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::087688905490:role/LabRole
  environment:
    TABLE_NAME_CINES: ${sls:stage}-tp_cines

functions:
  crear_cine:
    handler: LambdaCrearCine.lambda_handler
    memorySize: 1024
    events:
      - http:
          path: /cine/crear
          method: post
          cors: true
          integration: lambda
  buscar_cine:
    handler: LambdaBuscarCine.lambda_handler
    memorySize: 1024
    events:
      - https:
          path: /cine/buscar
          method: post
          cors: true
          integration: lambda
  modificar_cine:
    handler: LambdaModificarCine.lambda_handler
    memorySize: 1024
    events:
      - https:
          path: /cine/modificar
          method: put
          cors: true
          integration: lambda

resources:
  Resources:
    TablaCines:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME_CINES}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: cine_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: cine_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
